[workspace]
members = [
    "adventofcode2025/day1",
    "adventofcode2025/common",
    "adventofcode2025/day2",
    "adventofcode2025/day3",
    "adventofcode2025/day4",
    "adventofcode2025/day5",
]
resolver = "2"